CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
GPUS: (0,)
OUTPUT_DIR: 'runs/p2'
LOG_DIR: 'log/p2'
WORKERS: 3
PRINT_FREQ: 10

DATASET:
  DATASET: wire
  ROOT: /data1/VOC/segData/Record_data
  TEST_SET: 's0.0.4/val.txt'
  TRAIN_SET: 's0.0.4/train.txt'
  NUM_CLASSES: 2
MODEL:
  NAME: pidnet_s
  NUM_OUTPUTS: 2
  PRETRAINED: "pretrained_models/camvid/PIDNet_S_Camvid_Test.pt"
LOSS:
  USE_OHEM: true
  OHEMTHRES: 0.9
  OHEMKEEP: 131072
  BALANCE_WEIGHTS: [0.8, 1.0]
  SB_WEIGHTS: 1.0
TRAIN:
  IMAGE_SIZE:
  - 640
  - 480
  BASE_SIZE: 640
  BATCH_SIZE_PER_GPU: 24
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 120
  RESUME: false
  OPTIMIZER: sgd
  LR: 0.005
  WD: 0.0005
  MOMENTUM: 0.9
  NESTEROV: false
  FLIP: true
  MULTI_SCALE: true
  IGNORE_LABEL: 255
  SCALE_FACTOR: 16
TEST:
  IMAGE_SIZE:
  - 640
  - 480
  BASE_SIZE: 640
  BATCH_SIZE_PER_GPU: 8
  FLIP_TEST: false
  MULTI_SCALE: false
  MODEL_FILE: ''
  OUTPUT_INDEX: 1
